apiVersion: v1
kind: Template
metadata:
  annotations:
    description: istio para itzuli
    tags: istio, itzuli
  name: istio
objects:
- apiVersion: networking.istio.io/v1alpha3
  kind: Gateway
  metadata:
    name: ${HOST}-gw
    namespace: ${TARGET_NAMESPACE}
  spec:
    selector:
      istio: ingressgateway
    servers:
    - hosts:
      - ${HOST}.istio-ingressgateway-istio-system
      port:
        name: http-${HOST}
        number: 80
        protocol: HTTP
- apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  metadata:
    name: ${HOST}-vs
    namespace: ${TARGET_NAMESPACE}
  spec:
    gateways:
    - ${TARGET_NAMESPACE}/${HOST}-gw
    hosts:
    - ${HOST}.istio-ingressgateway-istio-system
    http:
    - match:
      - uri:
          prefix: ${VS_URI}
      mirror:
        host: ${HOST}
        port:
          number: 8080
        subset: rc
      mirrorPercentage:
        value: ${{MIRROR_PERCENT}}
      rewrite:
        uri: ' '
      route:
      - destination:
          host: ${HOST}
          port:
            number: 8080
          subset: stable
        weight: 100
- apiVersion: networking.istio.io/v1alpha3
  kind: ServiceEntry
  metadata:
    name: ${HOST}-se
    namespace: ${TARGET_NAMESPACE}
  spec:
    hosts:
    - ${HOST}.istio-ingressgateway-istio-system
    location: MESH_INTERNAL
    ports:
    - name: http-${HOST}
      number: 80
      protocol: http
    resolution: DNS
- apiVersion: networking.istio.io/v1alpha3
  kind: DestinationRule
  metadata:
    name: ${DR_NAME}
    namespace: ${TARGET_NAMESPACE}
  spec:
    host: ${HOST}
    subsets:
    - labels:
        version: stable
      name: stable
    - labels:
        version: rc
      name: rc
parameters:
- description: Target namespace
  name: TARGET_NAMESPACE
  required: true
  value: istio-sandbox
- description: DestinationRule Name
  name: DR_NAME
  required: true
  value: itzuli-adm-eu-es-dr
- description: VirtualService Name
  name: VS_NAME
  required: true
  value: itzuli-adm-eu-es-vs
- description: VirtualService URI
  name: VS_URI
  required: true
  value: /adm/eu2es
- description: mirrorPercentage
  name: MIRROR_PERCENT
  required: true
  value: '100'
- description: weight candidate
  name: WEIGHT_CANDIDATE
  required: true
  value: '0'
- description: weight stable
  name: WEIGHT_STABLE
  required: true
  value: '100'
- description: VirtualService Host
  name: HOST
  required: true
  value: itzuli-adm-eu-es
